### ISSUE TITLE
[bug] when choices is a set

### ISSUE THREAD

**Issue by Freed-Wu** [iterative/shtab#155] opened 2023-10-26 17:36 UTC
If we

```python
    parser.add_argument(
        "--color",
        choices={"auto", "always", "never"},
        default="auto",
        help="when to display color",
    )
```

It is legal, because argparse only check `choice in choices`, and it will be faster than choices is a list.

However, shtab will:

```
        File "/tmp/pip-build-env-xrs7p_m9/overlay/lib/python3.11/site-packages/shtab/__init__.py", line 795, in __call__
          print(complete(parent or parser, values, preamble=preamble))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xrs7p_m9/overlay/lib/python3.11/site-packages/shtab/__init__.py", line 784, in complete
          return completer(
                 ^^^^^^^^^^
        File "/tmp/pip-build-env-xrs7p_m9/overlay/lib/python3.11/site-packages/shtab/__init__.py", line 506, in complete_zsh
          "cmd": prog, "arguments": [
                                    ^
        File "/tmp/pip-build-env-xrs7p_m9/overlay/lib/python3.11/site-packages/shtab/__init__.py", line 507, in <listcomp>
          format_optional(opt, parser)
        File "/tmp/pip-build-env-xrs7p_m9/overlay/lib/python3.11/site-packages/shtab/__init__.py", line 488, in format_optional
          (choice_type2fn[opt.choices[0].type] if isinstance(opt.choices[0], Choice) else
                                                             ~~~~~~~~~~~^^^
      TypeError: 'set' object is not subscriptable
```

**Comment by casperdcl** [comment] 2023-12-01 23:46
Duplicate of https://github.com/iterative/shtab/issues/95#issuecomment-1476479655

According to https://docs.python.org/3/library/argparse.html#choices, `choices` must be a *sequence*. Sets are not sequences. `isinstance(set(), typing.Sequence) == False`.

**Closed by casperdcl** 2023-12-01 23:46 UTC
