### ISSUE TITLE
Can't make shtab work on Bash

### ISSUE THREAD

**Issue by avnaf** [iterative/shtab#62] opened 2021-12-02 12:23 UTC
[SO](https://stackoverflow.com/questions/70198570/shtab-tab-completion-not-working-after-following-instructions)

I tried adding autocomplete using [shtab][1] but it doesn't work :(

The completion file (/etc/bash_completion.d/shtab) looks ok, but hitting **TAB** does nothing

Reproduce:

 1. `virtualenv -p python3.6 venv && . venv/bin/activate`
 2. `pip install -U shtab`
 3. `shtab --shell=bash shtab.main.get_main_parser --error-unimportable | sudo tee /etc/bash_completion.d/shtab`

I changed the `"$BASH_COMPLETION_COMPAT_DIR"/shtab` into `/etc/bash_completion.d/shtab` because [it is not relevant anymore][2] (*though I did also run the original command*)

My environment:

 - Ubuntu 18.04
 - Python3.6
 - shtab==1.5.2
 - Bash 4.4.20

----------

Tried also on:

 1. zsh==5.4.2
 2. Docker (`docker run -it python /bin/bash`)

  [1]: https://github.com/iterative/shtab
  [2]: https://github.com/scop/bash-completion/commit/c41a76237bc9dcbfa326eeddd026b66d7646d91d

Is there an issue with my environment?

**Comment by casperdcl** [comment] 2021-12-02 12:57
Did you follow the [installation instructions](https://docs.iterative.ai/shtab/#installation), in particular checking your `~/.bashrc`?

**Comment by avnaf** [comment] 2021-12-02 15:35
Yes. My `~/.bashrc` does contain the relevant lines and I also ran the the `sudo apt install --reinstall bash-completion` just in case, but anyhow, I also tried it on `zsh` - so even if the issue was the bash_completion - `zsh` should have worked fine, and it didn't :(

**Comment by casperdcl** [comment] 2021-12-08 19:36
Ah `shtab` itself (unlike `git`) doesn't have any subcommands to complete. However, like `git` it does have options to complete.

- `shtab **TAB TAB**` won't have anything to suggest
- `shtab -**TAB TAB**` should work fine :)

probably a duplicate of #45. Happy to reopen if not.

**Closed by casperdcl** 2021-12-08 19:36 UTC

**Comment by avnaf** [comment] 2021-12-09 13:14
Indeed trying `shtab - <tab>` did work. However, I can't make it work on my script.

This is my full example, hope you can point to what is wrong:

bla.py
```python
#!/usr/bin/env python
import argparse

def get():
    p = argparse.ArgumentParser()
    p.add_argument('c')
    p.add_argument('-d')
    subs = p.add_subparsers()
    sub_a = subs.add_parser('a')
    sub_a.add_argument('a')
    sub_a.add_argument('--b')
    sub_b = subs.add_parser('b')
    sub_b.add_argument('b')
    sub_b.add_argument('--c')
    return p


if __name__ == '__main__':
    print(get().parse_args())
```

```bash
chmod +x bla.py
shtab -s bash -u bla.get | sudo tee /etc/bash_completion.d/bla
./bla.py <tab> # shows dir content
./bla.py - <tab> # nothing
```

This parser should have been completed on every level, but no completion / wrong completion is all I get...

Python3.6.9
Ubuntu18.04.5
Bash4.4.20
shtab==1.5.2

**Comment by casperdcl** [comment] 2021-12-09 18:17
you need to specify the program name. Either one of:

- `p = argparse.ArgumentParser(prog="bla.py")` or
- `shtab -s bash -u bla.get --prog bla.py`

**Comment by avnaf** [comment] 2021-12-10 06:25
@casperdcl there is a progress, however, not complete

Current status (after using `--prog bla.py`):
- ./bla.py <tab> # nothing (should have completed {a,b,d} based on the sub-parsers and the positional argument for the main parser
- ./bla.py - <tab> # completes to `-d, -h --help` which is much better

**Comment by casperdcl** [comment] 2021-12-10 09:00
you have a few bugs:

- clashing arg & option `c` & `--c`
- clashing arg & option `b` & `--b`
- missing help which implies a "hidden" command

```python
def get():
    p = argparse.ArgumentParser(prog="bla.py")
    p.add_argument('cp', help="a positional arg called cp")
    p.add_argument('-d', help="an option called d")
    subs = p.add_subparsers()

    # make required (py3.7 API change); vis. https://bugs.python.org/issue16308
    subs.required = True
    subs.dest = "subcommand"

    sub_a = subs.add_parser('a', help="a subcommand called a")
    sub_a.add_argument('a', help="a positional arg called a")
    sub_a.add_argument('--bo', help="an option called bo")

    sub_b = subs.add_parser('b', help="a subcommand called b")
    sub_b.add_argument('bp', help="a positional arg called bp")
    sub_b.add_argument('--co', help="an option called co")
    return p
```
